import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./navigation/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-rose-100"lang="en">
      {/*<Navigation />*/}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
